import { Group, Task } from './types'

type SeedGroup = Partial<Group> & {
  id: string
  title: string
  tasks: Array<Partial<Task> & { id: string; title: string; createdAt: string }>
}

export const seedData: SeedGroup[] = [
  {
    id: 'group-cleaning',
    title: 'ניקיון',
    color: 'purple',
    collapsed: false,
    order: 0,
    tasks: [
      {
        id: 'task-c1',
        title: 'לנקות את המטבח לעומק',
        assignee: 'אשתי',
        status: 'לא התחיל',
        priority: 'גבוה',
        dueDate: '2026-04-15',
        notes: 'כולל חיטוי הכיור ומגירות',
        createdAt: '2026-04-10T10:00:00Z',
        subtasks: [
          { id: 'st-c1a', title: 'לנקות כיור', done: false },
          { id: 'st-c1b', title: 'לנגב מגירות', done: false },
          { id: 'st-c1c', title: 'לשטוף רצפה', done: false },
        ],
        tags: [],
        recurring: 'weekly',
        order: 0,
      },
      {
        id: 'task-c2',
        title: 'לשאוב אבק בסלון ובחדרים',
        assignee: 'שנינו',
        status: 'בתהליך',
        priority: 'בינוני',
        dueDate: '2026-04-14',
        notes: '',
        createdAt: '2026-04-10T10:01:00Z',
        subtasks: [],
        tags: ['tag-weekly'],
        recurring: 'weekly',
        order: 1,
      },
      {
        id: 'task-c3',
        title: 'לנקות חלונות',
        assignee: 'יהודה',
        status: 'לא התחיל',
        priority: 'נמוך',
        dueDate: '2026-04-20',
        notes: 'חלונות חיצוניים בלבד',
        createdAt: '2026-04-10T10:02:00Z',
        subtasks: [],
        tags: [],
        recurring: 'monthly',
        order: 2,
      },
      {
        id: 'task-c4',
        title: 'לנקות שירותים ואמבטיה',
        assignee: 'שנינו',
        status: 'הושלם',
        priority: 'גבוה',
        dueDate: '2026-04-13',
        notes: '',
        createdAt: '2026-04-09T08:00:00Z',
        subtasks: [],
        tags: [],
        recurring: 'weekly',
        order: 3,
      },
      {
        id: 'task-c5',
        title: 'לארגן את הארון בחדר שינה',
        assignee: 'אשתי',
        status: 'תקוע',
        priority: 'נמוך',
        dueDate: '2026-04-18',
        notes: 'צריך לקנות קופסאות אחסון קודם',
        createdAt: '2026-04-08T09:00:00Z',
        subtasks: [
          { id: 'st-c5a', title: 'לקנות קופסאות', done: false },
          { id: 'st-c5b', title: 'למיין בגדים', done: false },
        ],
        tags: [],
        recurring: 'none',
        order: 4,
      },
    ],
  },
  {
    id: 'group-shopping',
    title: 'קניות',
    color: 'blue',
    collapsed: false,
    order: 1,
    tasks: [
      {
        id: 'task-s1',
        title: 'קניות שבועיות בסופר',
        assignee: 'שנינו',
        status: 'לא התחיל',
        priority: 'גבוה',
        dueDate: '2026-04-14',
        notes: 'לזכור: חלב, לחם, ביצים, ירקות לסלט',
        createdAt: '2026-04-12T07:00:00Z',
        subtasks: [
          { id: 'st-s1a', title: 'חלב ומוצרי חלב', done: true },
          { id: 'st-s1b', title: 'ירקות ופירות', done: false },
          { id: 'st-s1c', title: 'לחם ודגנים', done: false },
        ],
        tags: ['tag-weekly'],
        recurring: 'weekly',
        order: 0,
      },
      {
        id: 'task-s2',
        title: 'לקנות מדיח כלים חדש',
        assignee: 'יהודה',
        status: 'בתהליך',
        priority: 'גבוה',
        dueDate: '2026-04-20',
        notes: 'לבדוק ב-KSP ובאמזון',
        createdAt: '2026-04-10T11:00:00Z',
        subtasks: [],
        tags: ['tag-urgent'],
        recurring: 'none',
        order: 1,
      },
      {
        id: 'task-s3',
        title: 'לקנות בגדי קיץ לילדים',
        assignee: 'אשתי',
        status: 'לא התחיל',
        priority: 'בינוני',
        dueDate: '2026-04-25',
        notes: 'מידות: 6 ו-8',
        createdAt: '2026-04-11T12:00:00Z',
        subtasks: [],
        tags: [],
        recurring: 'none',
        order: 2,
      },
      {
        id: 'task-s4',
        title: 'לקנות מוצרי ניקיון',
        assignee: 'שנינו',
        status: 'הושלם',
        priority: 'בינוני',
        dueDate: '2026-04-13',
        notes: 'אקונומיקה, סבון כלים, מרכך',
        createdAt: '2026-04-09T09:00:00Z',
        subtasks: [],
        tags: [],
        recurring: 'monthly',
        order: 3,
      },
    ],
  },
  {
    id: 'group-kids',
    title: 'ילדים',
    color: 'green',
    collapsed: false,
    order: 2,
    tasks: [
      {
        id: 'task-k1',
        title: 'לרשום לחוג קיץ',
        assignee: 'אשתי',
        status: 'בתהליך',
        priority: 'גבוה',
        dueDate: '2026-04-16',
        notes: 'לבדוק: כדורגל, ציור, שחייה',
        createdAt: '2026-04-10T08:00:00Z',
        subtasks: [],
        tags: ['tag-urgent'],
        recurring: 'none',
        order: 0,
      },
      {
        id: 'task-k2',
        title: 'פגישת הורים בבית הספר',
        assignee: 'שנינו',
        status: 'לא התחיל',
        priority: 'גבוה',
        dueDate: '2026-04-17',
        notes: '17:30 בכיתה ד׳',
        createdAt: '2026-04-11T10:00:00Z',
        subtasks: [],
        tags: [],
        recurring: 'none',
        order: 1,
      },
      {
        id: 'task-k3',
        title: 'לסדר את פינת המשחקים',
        assignee: 'ילדים',
        status: 'לא התחיל',
        priority: 'נמוך',
        dueDate: '2026-04-15',
        notes: 'עם פיקוח של אחד ההורים',
        createdAt: '2026-04-10T09:00:00Z',
        subtasks: [],
        tags: [],
        recurring: 'none',
        order: 2,
      },
      {
        id: 'task-k4',
        title: 'לקנות ציוד בית ספר לשנה הבאה',
        assignee: 'אשתי',
        status: 'לא התחיל',
        priority: 'נמוך',
        dueDate: '2026-05-01',
        notes: 'לחכות לרשימה מבית הספר',
        createdAt: '2026-04-12T08:00:00Z',
        subtasks: [],
        tags: [],
        recurring: 'none',
        order: 3,
      },
      {
        id: 'task-k5',
        title: 'תור לרופא שיניים לילדים',
        assignee: 'אשתי',
        status: 'הושלם',
        priority: 'בינוני',
        dueDate: '2026-04-13',
        notes: 'שניהם קבעו ל-1 במאי',
        createdAt: '2026-04-08T10:00:00Z',
        subtasks: [],
        tags: [],
        recurring: 'none',
        order: 4,
      },
    ],
  },
  {
    id: 'group-maintenance',
    title: 'תחזוקה',
    color: 'orange',
    collapsed: false,
    order: 3,
    tasks: [
      {
        id: 'task-m1',
        title: 'לתקן ברז מטפטף בחדר רחצה',
        assignee: 'יהודה',
        status: 'תקוע',
        priority: 'גבוה',
        dueDate: '2026-04-14',
        notes: 'לקרוא לשרברב אם לא מסתדר',
        createdAt: '2026-04-09T07:00:00Z',
        subtasks: [],
        tags: ['tag-urgent'],
        recurring: 'none',
        order: 0,
      },
      {
        id: 'task-m2',
        title: 'לצבוע את הסלון',
        assignee: 'שנינו',
        status: 'לא התחיל',
        priority: 'נמוך',
        dueDate: '2026-05-15',
        notes: 'צבע: לבן שבור / אפור בהיר',
        createdAt: '2026-04-10T10:00:00Z',
        subtasks: [],
        tags: [],
        recurring: 'none',
        order: 1,
      },
      {
        id: 'task-m3',
        title: 'לבדוק מזגן לפני הקיץ',
        assignee: 'יהודה',
        status: 'לא התחיל',
        priority: 'גבוה',
        dueDate: '2026-04-22',
        notes: 'לקבוע טכנאי מזגנים',
        createdAt: '2026-04-11T11:00:00Z',
        subtasks: [],
        tags: [],
        recurring: 'none',
        order: 2,
      },
      {
        id: 'task-m4',
        title: 'להחליף נורות בפינת אוכל',
        assignee: 'יהודה',
        status: 'הושלם',
        priority: 'נמוך',
        dueDate: '2026-04-12',
        notes: 'LED E27',
        createdAt: '2026-04-07T08:00:00Z',
        subtasks: [],
        tags: [],
        recurring: 'none',
        order: 3,
      },
      {
        id: 'task-m5',
        title: 'לסדר גדר בגינה',
        assignee: 'שנינו',
        status: 'בתהליך',
        priority: 'בינוני',
        dueDate: '2026-04-19',
        notes: 'כמה עמודים רופפים',
        createdAt: '2026-04-10T12:00:00Z',
        subtasks: [],
        tags: [],
        recurring: 'none',
        order: 4,
      },
    ],
  },
  {
    id: 'group-finance',
    title: 'כספים',
    color: 'teal',
    collapsed: false,
    order: 4,
    tasks: [
      {
        id: 'task-f1',
        title: 'לשלם ארנונה',
        assignee: 'יהודה',
        status: 'לא התחיל',
        priority: 'גבוה',
        dueDate: '2026-04-15',
        notes: 'חיוב רבעוני — 3,200 ₪',
        createdAt: '2026-04-10T09:00:00Z',
        subtasks: [],
        tags: ['tag-urgent'],
        recurring: 'monthly',
        order: 0,
      },
      {
        id: 'task-f2',
        title: 'לעדכן תקציב חודשי',
        assignee: 'שנינו',
        status: 'בתהליך',
        priority: 'בינוני',
        dueDate: '2026-04-16',
        notes: 'לבדוק הוצאות חריגות החודש',
        createdAt: '2026-04-11T08:00:00Z',
        subtasks: [],
        tags: [],
        recurring: 'monthly',
        order: 1,
      },
      {
        id: 'task-f3',
        title: 'לבדוק ביטוח רכב לחידוש',
        assignee: 'יהודה',
        status: 'לא התחיל',
        priority: 'גבוה',
        dueDate: '2026-04-30',
        notes: 'להשוות מחירים בין חברות',
        createdAt: '2026-04-12T07:00:00Z',
        subtasks: [],
        tags: [],
        recurring: 'none',
        order: 2,
      },
      {
        id: 'task-f4',
        title: 'לפתוח חיסכון לילדים',
        assignee: 'שנינו',
        status: 'לא התחיל',
        priority: 'נמוך',
        dueDate: '2026-05-01',
        notes: 'לברר עם הבנק על קופת גמל להשקעה',
        createdAt: '2026-04-10T10:00:00Z',
        subtasks: [],
        tags: [],
        recurring: 'none',
        order: 3,
      },
      {
        id: 'task-f5',
        title: 'לסגור חשבון מיותר בסלקום',
        assignee: 'יהודה',
        status: 'הושלם',
        priority: 'נמוך',
        dueDate: '2026-04-10',
        notes: 'חיסכון: ~40 ₪ לחודש',
        createdAt: '2026-04-05T08:00:00Z',
        subtasks: [],
        tags: [],
        recurring: 'none',
        order: 4,
      },
    ],
  },
]
